In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml
from data_profiling import ProfileReport

E:\conda\envs\eda\Lib\site-packages\requests\__init__.py:92: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [2]:
data = fetch_openml(
    name="World-Top-Chess-Players-(August-2020)",
    version=1,
    as_frame=True,
    read_csv_kwargs={"low_memory": False}
)

df = data.frame

df.shape

(977687, 10)

In [3]:
df.head()

,Fide_id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
0,1503014,"Carlsen, Magnus",NOR,M,1990.0,GM,2863.0,2881.0,2886.0,NaN
1,2020009,"Caruana, Fabiano",USA,M,1992.0,GM,2835.0,2773.0,2711.0,NaN
2,4100018,"Kasparov, Garry",RUS,M,1963.0,GM,2812.0,2783.0,2801.0,i
3,8603677,"Ding, Liren",CHN,M,1992.0,GM,2791.0,2836.0,2788.0,NaN
4,4168119,"Nepomniachtchi, Ian",RUS,M,1990.0,GM,2784.0,2778.0,2785.0,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977687 entries, 0 to 977686
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Fide_id          977687 non-null  int64
 1   Name             977687 non-null  object
 2   Federation       977687 non-null  object
 3   Gender           977687 non-null  object
 4   Year_of_birth    943585 non-null  float64
 5   Title            19300 non-null   object
 6   Standard_Rating  363294 non-null  float64
 7   Rapid_rating     193348 non-null  float64
 8   Blitz_rating     139184 non-null  float64
 9   Inactive_flag    213193 non-null  object
dtypes: float64(4), int64(1), object(5)
memory usage: 74.6+ MB

In [5]:
# Построить EDA отчет и сохранить его в файл рядом с ноутбуком.

profile = ProfileReport(
    df,
    title="Chess Players EDA"
)

profile.to_file("Chess_EDA.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:07<01:07,  7.46s/it]
100%|██████████| 10/10 [00:10<00:00,  1.00s/it][A

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
# Количество совпадений имен

df.Name.value_counts()

Name
Manoj Kumar           20
Manish Kumar          17
Amit Kumar            15
Ivanov, Andrey        14
Mueller, Michael      14
                      ..
Zytkowiak, Michal      1
Zyto, Jakub            1
Zyubin, Konstantin     1
Zyukin, Jakov          1
Caruana, Fabiano       1
Name: count, Length: 951220, dtype: int64

In [7]:
# Просмотр множества одинаковых имен для проверки на ошибку в данных

df[df.Name == "Manoj Kumar"]

,Fide_id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
138139,46602607,Manoj Kumar,IND,M,1976.0,NaN,1789.0,NaN,NaN,i
176359,5082439,Manoj Kumar,IND,M,1978.0,NaN,1680.0,NaN,NaN,i
287134,35045164,Manoj Kumar,IND,M,1975.0,NaN,1322.0,NaN,NaN,i
302140,25176803,Manoj Kumar,IND,M,1967.0,NaN,1265.0,1273.0,NaN,NaN
304735,46690913,Manoj Kumar,IND,M,1976.0,NaN,1255.0,NaN,NaN,i
310954,5076579,Manoj Kumar,IND,M,1988.0,NaN,1230.0,NaN,NaN,i
312734,45041270,Manoj Kumar,IND,M,1972.0,NaN,1223.0,NaN,NaN,i
696048,46666923,Manoj Kumar,IND,M,2004.0,NaN,NaN,NaN,NaN,NaN
696049,46686010,Manoj Kumar,IND,M,1973.0,NaN,NaN,NaN,NaN,NaN
696050,25674390,Manoj Kumar,IND,M,1974.0,NaN,NaN,NaN,NaN,NaN
696051,25740377,Manoj Kumar,IND,M,1997.0,NaN,NaN,NaN,NaN,NaN
696052,25760882,Manoj Kumar,IND,M,1987.0,NaN,NaN,NaN,NaN,NaN
696053,25970321,Manoj Kumar,IND,M,1986.0,NaN,NaN,NaN,NaN,NaN
696054,25974165,Manoj Kumar,IND,M,1996.0,NaN,NaN,NaN,NaN,NaN
696055,25994620,Manoj Kumar,IND,M,1992.0,NaN,NaN,NaN,NaN,NaN
696056,25167944,Manoj Kumar,IND,M,1970.0,NaN,NaN,NaN,NaN,NaN
696057,33316600,Manoj Kumar,IND,M,1972.0,NaN,NaN,NaN,NaN,NaN
696058,33321159,Manoj Kumar,IND,M,1965.0,NaN,NaN,NaN,NaN,NaN
696059,33364915,Manoj Kumar,IND,M,1993.0,NaN,NaN,NaN,NaN,NaN
696060,33369615,Manoj Kumar,IND,M,1979.0,NaN,NaN,NaN,NaN,NaN

In [8]:
# Количество шахматистов, имеющих соответствующий титул

df.Title.value_counts()

Title
FM     8167
IM     3885
CM     1827
WFM    1744
GM     1721
WIM     838
WCM     800
WGM     317
WH        1
Name: count, dtype: int64

In [9]:
# Игрок с максимальным рейтингом в классическом режиме

df[df.Standard_Rating == df.Standard_Rating.max()]

,Fide_id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
0,1503014,"Carlsen, Magnus",NOR,M,1990.0,GM,2863.0,2881.0,2886.0,NaN

In [10]:
# Игрок с максимальным рейтингом в быстром режиме

df[df.Rapid_rating == df.Rapid_rating.max()]

,Fide_id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
0,1503014,"Carlsen, Magnus",NOR,M,1990.0,GM,2863.0,2881.0,2886.0,NaN

In [11]:
# Игрок с максимальным рейтингом в блиц режиме

df[df.Blitz_rating == df.Blitz_rating.max()]

,Fide_id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
19,2016192,"Nakamura, Hikaru",USA,M,1987.0,GM,2736.0,2829.0,2900.0,NaN

In [12]:
# Игроки с отстутсвием какого либо рейтинга и титула

df[(df.Standard_Rating.isna()) & (df.Title.isna() == True)]

,Fide_id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
363294,9018158,9018140,MAR,M,2001.0,NaN,NaN,NaN,NaN,NaN
363295,10688862,"A Abdel Maabod, Hoda",EGY,F,2009.0,NaN,NaN,NaN,NaN,NaN
363296,10224084,"A B M Hasibuzzaman, Tapan",BAN,M,1977.0,NaN,NaN,NaN,NaN,NaN
363297,10245154,"A B M Jobair, Hossain",BAN,M,1998.0,NaN,NaN,1599.0,NaN,NaN
363298,10243054,"A B M Mustakim, Chowdhury",BAN,M,2013.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
977682,21024650,"Zywicka, Amelia",POL,F,2009.0,NaN,NaN,NaN,NaN,NaN
977683,21038465,"Zyzanski, Alan",POL,M,2009.0,NaN,NaN,NaN,NaN,NaN
977684,21038473,"Zyzanski, Sebastian",POL,M,1976.0,NaN,NaN,1469.0,NaN,NaN
977685,21052492,"Zyzik, Adam",POL,M,2010.0,NaN,NaN,NaN,NaN,NaN
977686,21045437,"Zyzniewski, Tomasz",POL,M,1988.0,NaN,NaN,NaN,NaN,NaN

In [13]:
# Игроки с отстутсвием какого либо рейтинга, но с титулом

df[(df.Standard_Rating.isna()) & (df.Title.isna() == False)]

,Fide_id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
366367,16100727,"Abdirahin, Abdullahi Mohamed",SOM,M,1996.0,CM,NaN,NaN,NaN,NaN
377183,9401016,"Ahmed, Abdo",YEM,M,1999.0,FM,NaN,NaN,NaN,NaN
382901,9304495,"Al Mansouri, Moza",UAE,F,2000.0,WFM,NaN,NaN,NaN,NaN
383955,9400737,"Al-Ameri, Ahmed Abdo",YEM,M,NaN,CM,NaN,NaN,NaN,NaN
384064,7600143,"Al-Mohamed, Wesam",SYR,M,1997.0,FM,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
945299,6500595,"Villegas Loaiza, Meylin",CRC,F,1979.0,WIM,NaN,NaN,NaN,NaN
947054,14317842,"Visser, Anika",RSA,F,2005.0,WCM,NaN,NaN,NaN,NaN
959634,6508588,"Yagnyatinskiy, Maxim",CRC,M,2005.0,CM,NaN,NaN,NaN,NaN
959635,6508596,"Yagnyatinskiy, Vlad",CRC,M,2007.0,CM,NaN,NaN,NaN,NaN
964717,5813301,"Yip, Fong Ling",SGP,F,1968.0,WFM,NaN,NaN,NaN,NaN

In [14]:
# Неактивные игроки

df[~df.Inactive_flag.isna()]

,Fide_id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
2,4100018,"Kasparov, Garry",RUS,M,1963.0,GM,2812.0,2783.0,2801.0,i
17,4101588,"Kramnik, Vladimir",RUS,M,1975.0,GM,2753.0,2756.0,2797.0,i
48,11600098,"Rausis, Igors",FID,M,1961.0,IM,2685.0,2421.0,2527.0,i
64,700070,"Polgar, Judit",HUN,F,1976.0,GM,2675.0,2646.0,2736.0,wi
66,702218,"Gyimesi, Zoltan",HUN,M,1977.0,GM,2674.0,NaN,NaN,i
...,...,...,...,...,...,...,...,...,...,...
363267,25988336,Yuvanesh S,IND,M,2008.0,NaN,0.0,NaN,NaN,i
363282,34344977,"Zhuk, Ilya",RUS,M,2009.0,NaN,0.0,1138.0,1019.0,i
363283,25124498,Zid Neo,IND,M,2012.0,NaN,0.0,NaN,NaN,i
363286,34348166,"Zinnurov, Amir",RUS,M,2010.0,NaN,0.0,NaN,NaN,i
363290,12824550,"Zubavicius, Kajus",LTU,M,2007.0,NaN,0.0,1258.0,1196.0,i

In [15]:
# Медианный рейтинг среди гроссмейстеров

df[df.Title == "GM"].Standard_Rating.median()

np.float64(2503.0)

In [16]:
# Медианный рейтинг среди мастеров FIDE

df[df.Title == "FM"].Standard_Rating.median()

np.float64(2262.0)

In [17]:
# Медианный рейтинг среди игроков без рейтинга

df[df.Title.isna()].Standard_Rating.median()

np.float64(1638.0)

In [18]:
# Последние 5 гроссмейстеров в наборе данных

df[df.Title == "GM"].tail()

,Fide_id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
22706,2000555,"Kaufman, Lawrence",USA,M,1947.0,GM,2188.0,NaN,2186.0,NaN
27488,14500094,"Cebalo, Miso",CRO,M,1945.0,GM,2160.0,2344.0,2176.0,NaN
30444,1203363,"Suba, Mihai",ESP,M,1947.0,GM,2146.0,2413.0,2164.0,NaN
31497,2900238,"Spiridonov, Nikola",BUL,M,1938.0,GM,2141.0,NaN,NaN,NaN
40824,4140249,"Malinin, Vasily B.",RUS,M,1956.0,GM,2100.0,1861.0,1911.0,NaN

In [19]:
# Первые 5 международных мастеров в наборе данных

df[df.Title == "IM"].head()

,Fide_id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
48,11600098,"Rausis, Igors",FID,M,1961.0,IM,2685.0,2421.0,2527.0,i
345,8600783,"Yin, Hao",CHN,M,1979.0,IM,2583.0,NaN,NaN,i
490,4262875,"Theodorou, Nikolas",GRE,M,2000.0,IM,2554.0,2559.0,2351.0,NaN
552,4156013,"Obolenskikh, Dmitry",RUS,M,1985.0,IM,2544.0,2627.0,2559.0,NaN
597,14502070,"Topalovic, Zlatko",CRO,M,1965.0,IM,2539.0,NaN,NaN,i